# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(739, 359)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.COM_box = QtWidgets.QComboBox(self.centralwidget)
        self.COM_box.setObjectName("COM_box")
        self.COM_box.addItem("")
        self.verticalLayout_2.addWidget(self.COM_box)
        self.protocol_path = QtWidgets.QLineEdit(self.centralwidget)
        self.protocol_path.setMinimumSize(QtCore.QSize(500, 0))
        self.protocol_path.setObjectName("protocol_path")
        self.verticalLayout_2.addWidget(self.protocol_path)
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setObjectName("username")
        self.verticalLayout_2.addWidget(self.username)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_3.addWidget(self.connect_button)
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setObjectName("load_button")
        self.verticalLayout_3.addWidget(self.load_button)
        self.username_button = QtWidgets.QPushButton(self.centralwidget)
        self.username_button.setObjectName("username_button")
        self.verticalLayout_3.addWidget(self.username_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setMinimumSize(QtCore.QSize(0, 100))
        self.start_button.setCheckable(False)
        self.start_button.setChecked(False)
        self.start_button.setObjectName("start_button")
        self.verticalLayout_4.addWidget(self.start_button)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setMinimumSize(QtCore.QSize(0, 100))
        self.save_button.setObjectName("save_button")
        self.verticalLayout_4.addWidget(self.save_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.experiment_status = QtWidgets.QLabel(self.centralwidget)
        self.experiment_status.setObjectName("experiment_status")
        self.horizontalLayout_3.addWidget(self.experiment_status)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.protocol_status = QtWidgets.QLabel(self.centralwidget)
        self.protocol_status.setObjectName("protocol_status")
        self.horizontalLayout_3.addWidget(self.protocol_status)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.arduino_status = QtWidgets.QLabel(self.centralwidget)
        self.arduino_status.setObjectName("arduino_status")
        self.horizontalLayout_3.addWidget(self.arduino_status)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Select COM Adruino"))
        self.label_3.setText(_translate("MainWindow", "Select Protocol file"))
        self.label_4.setText(_translate("MainWindow", "Experimenter name"))
        self.COM_box.setItemText(0, _translate("MainWindow", "COM5"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.load_button.setText(_translate("MainWindow", "Load"))
        self.username_button.setText(_translate("MainWindow", "Save"))
        self.start_button.setText(_translate("MainWindow", "Start Experiment"))
        self.save_button.setText(_translate("MainWindow", "Save Experiment"))
        self.experiment_status.setText(_translate("MainWindow", "Experiment not running"))
        self.protocol_status.setText(_translate("MainWindow", "Protocole file not set"))
        self.arduino_status.setText(_translate("MainWindow", "Arduino Not Connected"))
